columns:
  - name: user_id
    dtype: int
    constraints:
      - constraint: not_null
        value: true
      - constraint: unique
        value: true
      - constraint: ge
        value: 1
  - name: score
    dtype: float
    constraints:
      - constraint: not_null
        value: true
      - constraint: ge
        value: 0.0
      - constraint: le
        value: 100.0
  - name: score_with_nulls
    dtype: float
  - name: age
    dtype: int
    constraints:
      - constraint: ge
        value: 0
      - constraint: le
        value: 120
  - name: age_with_nulls
    dtype: int
  - name: is_active
    dtype: bool
  - name: is_active_with_nulls
    dtype: bool
  - name: country
    dtype: str
    constraints:
      - constraint: not_null
        value: true
  - name: country_with_nulls
    dtype: str
